# Generated by Django 4.1.1 on 2022-11-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reglink',
            name='lead_reglink',
            field=models.CharField(default='NoVnX4epQwpcIx0I8Z5NOeZk1CgF09', max_length=150, verbose_name='Lead Registration Link'),
        ),
    ]
