# Generated by Django 4.1.1 on 2022-12-15 15:19

import app.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/logicmorph8.png', upload_to=app.models.profile.image_path),
        ),
    ]
