# Generated by Django 4.1.1 on 2022-12-16 13:58

import app.models.profile
from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMtheme',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('is_logicmorph_staff', models.BooleanField(default=False)),
                ('is_dark_theme', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/logicmorph2.png', upload_to=app.models.profile.image_path),
        ),
    ]
