# Generated by Django 4.1.1 on 2022-12-16 14:15

import app.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appsettings_delete_lmtheme_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/logicmorph2.png', upload_to=app.models.profile.image_path),
        ),
    ]
