# Generated by Django 4.1.1 on 2022-10-15 12:10
import hashid_field.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
