# Generated by Django 4.1.1 on 2022-10-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_lead_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
