# Generated by Django 4.1.1 on 2022-12-16 14:17

import app.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='is_logicmorph_staff',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/logicmorph1.png', upload_to=app.models.profile.image_path),
        ),
    ]
