# Generated by Django 4.1.1 on 2022-12-16 14:20

import app.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_appsettings_is_logicmorph_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/logicmorph3.png', upload_to=app.models.profile.image_path),
        ),
    ]
