# Generated by Django 4.1.1 on 2022-10-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project_alter_lead_options_profile_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='profile',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default='1234', on_delete=django.db.models.deletion.CASCADE, related_name='client_project', to='app.client'),
        ),
    ]
