# Generated by Django 4.1.1 on 2022-10-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_client_profile_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
    ]
