# Generated by Django 4.1.1 on 2022-12-16 14:25

import app.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appsettings',
            new_name='Appsetting',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/logicmorph6.png', upload_to=app.models.profile.image_path),
        ),
    ]
