# Generated by Django 4.1.1 on 2022-10-17 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='client_project', to='app.client'),
            preserve_default=False,
        ),
    ]
