# Generated by Django 4.1.1 on 2022-10-17 13:50
import datetime

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_project_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                default=1234,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_project",
                to="app.client",
            ),
        ),
    ]
