# Generated by Django 4.1.1 on 2022-10-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='client_project', to='app.client'),
        ),
    ]
