# Generated by Django 4.0.8 on 2023-01-25 15:47

import app.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/logicmorph6.png', upload_to=app.models.profile.image_path),
        ),
    ]
