# Generated by Django 4.1.1 on 2022-10-17 13:52
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_project_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="client",
        ),
    ]
