# Generated by Django 4.1.1 on 2022-10-17 13:59
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_project_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_profile",
                to="app.client",
            ),
            preserve_default=False,
        ),
    ]
