# Generated by Django 4.1.1 on 2022-10-17 16:51

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50),
        ),
    ]
