# Generated by Django 4.1.1 on 2022-10-17 17:07

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_lead_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50, protected=True),
        ),
    ]
