# Generated by Django 4.1.1 on 2022-10-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_lead_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='project',
        ),
    ]
