# Generated by Django 4.1.1 on 2022-10-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_developer_profile_remove_developer_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone_no',
            field=models.IntegerField(blank=True),
        ),
    ]
