# Generated by Django 4.1.1 on 2022-10-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_client_telephone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
