# Generated by Django 4.1.1 on 2022-10-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_lead_updated_at_alter_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='profile',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to='app.profile'),
            preserve_default=False,
        ),
    ]
