# Generated by Django 4.1.1 on 2022-10-20 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_developer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='project',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='developer_project', to='app.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
