# Generated by Django 4.0.10 on 2023-07-24 04:37

import app.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/logicmorph1.png', upload_to=app.models.profile.image_path),
        ),
    ]
