# Generated by Django 4.1.1 on 2026-09-19 06:58

import app.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=app.models.profile.default_avatar, upload_to=app.models.profile.image_path),
        ),
    ]
