# Generated by Django 4.1.1 on 2022-10-12 09:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="entity_name",
            field=models.CharField(max_length=100, verbose_name="Subject"),
        ),
    ]
