# Generated by Django 4.1.1 on 2022-10-14 17:20
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customer_first_name_alter_customer_last_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
