# Generated by Django 4.1.1 on 2022-10-15 12:10

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False),
        ),
    ]
